version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /web
    ignore:
      - dependency-name: primevue
        versions: ['>=5']
      - dependency-name: '@primeuix/themes'
        versions: ['>=2']
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: /deploy
    schedule:
      interval: weekly
