import { expect, test } from '../../web/node_modules/@playwright/test'

test('design standards, localized navigation, charts and safe dialog dismissal', async ({ page }, info) => {
  test.setTimeout(90000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'warning' && message.text().includes('Not found')) errors.push(message.text()) })
  await page.goto('/test.html')
  await expect(page.locator('.line-chart svg')).toBeVisible()
  await expect(page.locator('.donut-chart svg')).toBeVisible()
  expect(await page.locator('body').evaluate(el => getComputedStyle(el).fontFamily)).toContain('Inter Variable')
  if (info.project.name === 'desktop') {
    await page.getByRole('button', {name:'收起导航',exact:true}).click()
    await expect(page.locator('.gallery')).toHaveClass(/nav-collapsed/)
    await page.reload()
    await expect(page.getByRole('button', {name:'展开导航',exact:true})).toHaveAttribute('aria-expanded','false')
    await page.getByRole('button', {name:'展开导航',exact:true}).click()
  } else {
    await page.getByRole('button', {name:'打开导航',exact:true}).click()
    await expect(page.getByRole('dialog', {name:'导航',exact:true})).toBeVisible()
    await page.getByRole('dialog').getByRole('link', {name:'输入与选择'}).click()
    await expect(page.getByRole('dialog')).not.toBeVisible()
  }
  const preview = page.getByRole('button',{name:'预览新建弹窗',exact:true})
  await preview.click()
  const close = page.getByRole('button',{name:'关闭弹窗',exact:true})
  await expect(close.locator('svg')).toBeVisible()
  expect(await close.evaluate(el=>getComputedStyle(el).borderTopWidth)).toBe('0px')
  await page.mouse.click(4,4)
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.getByRole('button',{name:'编辑弹窗示例',exact:true}).click()
  await page.getByRole('dialog').getByLabel('工作空间名称').fill('Unsaved edit')
  await page.mouse.click(4,4)
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button',{name:'放弃修改',exact:true}).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.getByRole('button',{name:'危险操作',exact:true}).click()
  await page.mouse.click(4,4)
  await expect(page.getByRole('alertdialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('alertdialog')).toBeVisible()
  await page.getByRole('button',{name:'取消',exact:true}).click()
  const tabs = page.locator('.chart-tabs')
  const before = await tabs.locator('.p-tablist-active-bar').getAttribute('style')
  await tabs.getByRole('tab',{name:'用户增长',exact:true}).click()
  await expect(tabs.getByRole('tab',{name:'用户增长',exact:true})).toHaveAttribute('aria-selected','true')
  await expect(tabs.locator('.p-tablist-active-bar')).not.toHaveAttribute('style', before!)
  await page.getByRole('button',{name:'移除协议 Responses',exact:true}).click()
  await expect(page.getByRole('button',{name:'移除协议 Responses',exact:true})).toHaveCount(0)
  const view = page.getByRole('button',{name:'查看',exact:true}).first()
  await view.hover()
  expect(await view.evaluate(el=>getComputedStyle(el).boxShadow)).toBe('none')
  await page.getByRole('combobox',{name:'Language / 语言'}).click()
  await page.getByRole('option',{name:'English',exact:true}).click()
  await expect(page.locator('html')).toHaveAttribute('lang','en')
  await expect(page.getByRole('heading',{name:'Core trends',exact:true})).toBeVisible()
  await expect(page.getByLabel('Workspace name',{exact:true})).toBeVisible()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('lang','en')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:`test-results/standards-${info.project.name}-en.png`,fullPage:true})
  await page.getByRole('button',{name:/Switch to .* theme/}).click()
  await page.screenshot({path:`test-results/standards-${info.project.name}-alternate.png`,fullPage:true})
  expect(errors).toEqual([])
})
