name: Feature request
description: Propose a use case and expected behavior.
body:
  - type: textarea
    id: proposal
    attributes:
      label: Use case and proposal
    validations:
      required: true
